### ISSUE TITLE
Location check overflow

### ISSUE THREAD

**Issue by alwaysintreble** [Ijwu/Archipelago.RiskOfRain2#4]
After completing all checks or forfeiting, upon reconnect location checks will continue to be sent to the server and iterate the check counter higher than the max.

**Comment by Ijwu** [comment]
Just a few questions: YAML used to generate? Which version of AP? Which version of RoR AP Client? Are you reconnecting to the same session after completion/forfeit?

I'm pretty sure the client doesn't care whether it's connecting to a completed slot or not but AP shouldn't tell the client that it's missing any checks once it connects, if it's complete.

**Comment by alwaysintreble** [comment]
Version 1.01 of the client. I can send you the YAML when I get home but I
was able to reproduce this with different settings. Tried it on both the
0.1.7 release and my personal build of AP source. The problem was occurring
both on a successful forfeit and was able to reproduce it by just finishing
checks then returning to menu then reconnecting to the same server. And
also by dying

**Comment by Ijwu** [comment]
Someone reconnecting to a forfeited slot is pretty low on my list of priorities. It's undefined behavior, as far as I'm concerned, and should actually probably be handled by the AP server.
